name: mysql_flutter
description: Native MySQL client written in Dart. Tested with MySQL Percona Server (5.7, 8), MariaDB (10). Supports TLS.
version: 0.0.1
homepage: https://github.com/gopelkujo/mysql_flutter
repository: https://github.com/gopelkujo/mysql_flutter
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.6 <3.0.0"


dev_dependencies:
  hex: ^0.2.0
  lints: ^1.0.0
  test: ^1.20.1
dependencies: 
  buffer: ^1.1.1
  crypto: ^3.0.1
  tuple: ^2.0.0